### ISSUE TITLE
No implementation found for method register on channel twilio_voice_flutter

### ISSUE THREAD

**Issue by qzmmdsl** [DevCodeSpace/twilio_voice_flutter#1]
No implementation found for method register on channel twilio_voice_flutter
![1726055013949](https://github.com/user-attachments/assets/935d367f-00d9-445d-8a09-6c97d0b02608)

**Comment by DevCodeSpace** [comment]
@qzmmdsl Thank you for bringing this to my attention!

I am currently addressing the issue and will get back to you shortly with an updated version. I appreciate your feedback!

**Comment by DevCodeSpace** [comment]
@qzmmdsl I’m glad to inform you that the issue has been resolved. You can now update the dependency to version 0.0.3, and everything should work properly.

If you have any further questions or need assistance, feel free to reach out!

Thanks!
