### ISSUE TITLE
I am using correct phone number with +91 country code but still getting exception 

### ISSUE THREAD

**Issue by rohit0713** [DevCodeSpace/twilio_voice_flutter#3]
W/System.err(25351): com.twilio.voice.CallException: Not Found
I/TwilioUtils(25351): onConnectFailure. Error: Not Found
D/TwilioVoiceFlutter(25351): onConnectFailure. Error: Not Found

**Comment by DevCodeSpace** [comment]
@rohit0713  Please ensure that the country code and phone number are entered without any spaces. Let me know if you're still encountering issues after this adjustment.
