### ISSUE TITLE
How to get call SID?

### ISSUE THREAD

**Issue by Dinesh-Sowndar** [DevCodeSpace/twilio_voice_flutter#5]

**Comment by DevCodeSpace** [comment]
@Dinesh-Sowndar  You can retrieve the Call SID from the TwilioVoiceFlutterCall object, which is part of the TwilioVoiceFlutterEvent event listener, using the id property. Please note that the Call SID will be null until the call is in the RINGING state.

**Comment by Dinesh-Sowndar** [comment]
@DevCodeSpace It works. Thank you
